### ISSUE TITLE
Definition of convection in high dimensional burgers equation

### ISSUE THREAD

**Issue by qiauil** [Ceyron/exponax#43]
Hi! Felix,

I think there might be an issue with the burgers equation.

The convection term of the burgers equation is defined as 

$$
 \frac{1}{2} \nabla \cdot \left( u \otimes u \right) 
$$

However, according to Wikipedia, the definition should be 

$$
u \cdot \nabla u
$$

Note that $$u \cdot \nabla u =  \frac{1}{2} \nabla \cdot \left( u \otimes u \right) $$ only hold for 1d case. For high-dimensional cases,

$$
\nabla \cdot \left( u \otimes u \right) = u \cdot \nabla u + u\nabla \cdot u
$$

For example, in 3d case the x component of $\nabla \cdot \left( u \otimes u \right)$ is:

$$
u_x\frac{\partial u_x}{\partial x}
+u_y\frac{\partial u_x}{\partial y}
+u_z\frac{\partial u_x}{\partial z}
+u_x(\frac{\partial u_x}{\partial x}
+\frac{\partial u_y}{\partial y}
+\frac{\partial u_z}{\partial z})
$$

while the x component of $u \cdot \nabla u$ is only the first part, i.e., 

$$
u_x\frac{\partial u_x}{\partial x}
+u_y\frac{\partial u_x}{\partial y}
+u_z\frac{\partial u_x}{\partial z}
$$

In a word,  $$u \cdot \nabla u =  \nabla \cdot \left( u \otimes u \right) $$ if u is divergence-free, i.e., $\nabla \cdot u =0$. Otherwise $u \cdot \nabla u=\nabla \cdot \left( u \otimes u \right) - u\nabla \cdot u \neq \frac{1}{2}\nabla \cdot \left( u \otimes u \right)$

**Comment by qiauil** [comment]
Hi, Felix,

I think it should work; we need to make it clear in the docstring, and then It should be all fine for the users to choose!

**Comment by Ceyron** [comment]
Amazing, 
do you want to make the corresponding changes in #45 ?

**Comment by qiauil** [comment]
Hi, Felix.

I have added the new feature in #45; please have a check on it.

**Comment by qiauil** [comment]
Hi, Felix,

The new PR is added as #46, please have a check.

**Comment by Ceyron** [comment]
PR is merged.
